import { createFileRoute, Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Mail, FileText, ListChecks, Search, MessagesSquare, Sparkles, ArrowRight, AlertTriangle } from "lucide-react";

export const Route = createFileRoute("/_authenticated/dashboard")({
  component: Dashboard,
});

const tools = [
  { url: "/email", title: "Smart Email Generator", desc: "Draft polished emails in seconds with the right tone.", icon: Mail },
  { url: "/meeting", title: "Meeting Notes Summarizer", desc: "Turn raw notes into decisions, actions, and next steps.", icon: FileText },
  { url: "/tasks", title: "AI Task Planner", desc: "Break goals into prioritized, time-boxed plans.", icon: ListChecks },
  { url: "/research", title: "AI Research Assistant", desc: "Structured briefings on any topic, fast.", icon: Search },
  { url: "/chat", title: "AI Chatbot", desc: "Open-ended conversations with multi-thread memory.", icon: MessagesSquare },
];

function Dashboard() {
  return (
    <div className="mx-auto w-full max-w-6xl p-6">
      <div className="mb-8 flex flex-col gap-2">
        <div className="inline-flex w-fit items-center gap-2 rounded-full border border-border/60 bg-card/50 px-3 py-1 text-xs text-muted-foreground">
          <Sparkles className="h-3 w-3 text-primary" />
          Welcome to Pulse
        </div>
        <h1 className="text-3xl font-semibold tracking-tight">Your AI workplace, in one place</h1>
        <p className="max-w-2xl text-muted-foreground">
          Draft, summarize, plan, research, and chat — all powered by AI, designed for busy
          professionals.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link key={t.url} to={t.url}>
            <Card className="group h-full p-5 transition-all hover:border-primary/50 hover:shadow-[var(--shadow-glow)]">
              <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-primary to-[var(--primary-glow)] text-primary-foreground">
                <t.icon className="h-5 w-5" />
              </div>
              <h3 className="mb-1 font-semibold">{t.title}</h3>
              <p className="text-sm text-muted-foreground">{t.desc}</p>
              <div className="mt-4 flex items-center gap-1 text-xs text-primary opacity-0 transition-opacity group-hover:opacity-100">
                Open <ArrowRight className="h-3 w-3" />
              </div>
            </Card>
          </Link>
        ))}
      </div>

      <Card className="mt-8 flex items-start gap-3 border-amber-500/20 bg-amber-500/5 p-4">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
        <div className="text-sm">
          <p className="font-medium text-foreground">Responsible AI</p>
          <p className="text-muted-foreground">
            Outputs are generated by AI and may contain inaccuracies or biases. Always review
            content before sharing externally, and avoid pasting confidential or sensitive
            data unless your organization permits it.
          </p>
        </div>
      </Card>
    </div>
  );
}